### ISSUE TITLE
 Get event when it is being written

### ISSUE THREAD

**Issue by Juanperezc** [clue/php-term-react#25]
Hello clue, is it possible to get the event when it is being written to pause the loop in some way? for example while there is a loop with a counter increasing in the following way

`$cont = 0;
   $loop->addPeriodicTimer(1, function () use (&$cont){
       $cont++;
    echo $cont.PHP_EOL;
   });`

If you write something in the console, the text will be lost between iterations of the cycle and counter. What I want is to pause that cycle while I write

**Comment by clue** [comment]
This is a very good question! Yes, printing text to the terminal will overwrite your current input buffer. This means that you will have to take care of receiving the individual key presses and restoring the incomplete input buffer when you write to the terminal again.

Of course, you don't have to do this all yourself :-) This is exactly why I've created https://github.com/clue/php-stdio-react

I hope this helps :+1:
